workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: "com.yourcompany.yourapp"       # استبدل باسم الباكيج الخاص بتطبيقك
        IOS_DEVELOPMENT_TEAM: "22"           # استبدل بالـ Team ID من حساب Apple Developer
      node: stable
      ruby: 3.2.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install ios
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace Shatably.xcworkspace -scheme Shatably -configuration Release -allowProvisioningUpdates
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
