workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: "com.yourcompany.shatably"
        IOS_DEVELOPMENT_TEAM: "YOUR_TEAM_ID"
      node: stable
      ruby: 3.2.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -project Shatably.xcodeproj -scheme Shatably -configuration Release -destination 'generic/platform=iOS' -allowProvisioningUpdates
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
