import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    // marginBottom: 80, // عشان البار السفلي
  },
  backgroundImage: {
    width: '100%',
    height: height * 0.35,
  },
  statusBarBackground: {
  },
  topIconsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  iconButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconImage: {
    width: 27,
    height: 27,
  },
  headerContainer: {
    paddingHorizontal: 40,
    marginTop: 20,
    marginBottom: 30,
  },
  headerText: {
    fontFamily: 'Alexandria',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  searchBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    height: 56,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    textAlign: 'right',
    paddingRight: 10,
    color: '#333',
  },
  searchIconContainer: {
    width: 24,
    height: 24,
  },
  searchIcon: {
    width: 24,
    height: 24,
  },
  // Services Section Styles
  servicesContainer: {
    backgroundColor: '#ffffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: -20,
    paddingTop: 30,
    paddingBottom: 10,
  },
  servicesRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 10,
  },
  serviceItem: {
    alignItems: 'center',
    width: 62,
  },
  serviceIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 15,
    backgroundColor: '#ffffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  serviceIcon: {
    width: 30,
    height: 30,
  },
  serviceTitle: {
    fontFamily: 'Alexandria',
    fontSize: 12,
    textAlign: 'center',
    color: '#333',
  },
  // Projects Section Styles
  projectsContainer: {
    backgroundColor: '#fff',
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  projectsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingHorizontal: 5,
  },
  projectsTitle: {
    fontFamily: 'Alexandria',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 12,
    color: '#E68314',
    marginLeft: 5,
  },
  arrowIcon: {
    width: 12,
    height: 12,
    tintColor: '#E68314',
  },
  projectsScrollView: {
    paddingVertical: 3,
  },
  projectCard: {
    width: 250,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    padding: 15,
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  projectImage: {
    width: '100%',
    height: 110,
    borderRadius: 8,
    marginBottom: 12,
  },
  projectName: {
    fontFamily: 'Alexandria',
    fontWeight: '600',
    fontSize: 14,
    color: '#000',
    marginBottom: 10,
    textAlign: 'right',
  },
  // Stage Container
  stageContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  statusBadge: {
    backgroundColor: '#8BADB1',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 10,
    color: '#FFFFFF',
  },
  stageTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stageText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 12,
    color: '#666',
    marginLeft: 5,
    textAlign: 'right',
  },
  clockIcon: {
    width: 14,
    height: 14,
  },
  // Progress Container
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  progressTextContainer: {
    width: '20%',
  },
  progressText: {
    fontFamily: 'Alexandria',
    fontWeight: '600',
    fontSize: 12,
    color: '#8BADB1',
    textAlign: 'left',
  },
  progressBarContainer: {
    width: '75%',
  },
  progressBackground: {
    width: '100%',
    height: 6,
    backgroundColor: '#EDEFF4',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#8BADB1',
    borderRadius: 3,
  },
  // Companies Section Styles
  companiesContainer: {
    backgroundColor: '#fff',
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  companiesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingHorizontal: 5,
  },
  companiesTitle: {
    fontFamily: 'Alexandria',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 16,
    color: '#000',
  },
  companiesScrollView: {
    paddingVertical: 3,
  },
  companyCard: {
    width: 280,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  companyImageContainer: {
    position: 'relative',
  },
  companyImage: {
    width: '100%',
    height: 120,
  },
  dotsIconContainer: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotsIcon: {
    width: 20,
    height: 20,
  },
  companyInfo: {
    padding: 12,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  companyTitle: {
    fontFamily: 'Alexandria',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    color: '#000',
    flex: 1,
    textAlign: 'right',
  },
  categoryBadge: {
    backgroundColor: '#FFE4C7',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
  },
  categoryText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 10,
    color: '#E68314',
  },
  companyDescription: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starIcon: {
    width: 12,
    height: 12,
    marginLeft: 2,
  },
  ratingText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 10,
    color: '#666',
    marginLeft: 4,
  },
  reviewsText: {
    fontFamily: 'Alexandria',
    fontWeight: '400',
    fontSize: 10,
    color: '#666',
  },
  promotionContainer: {
  backgroundColor: '#fff',
  paddingVertical: 20,
  paddingHorizontal: 15,
},
gradientCard: {
  flexDirection: 'row',
  backgroundColor: '#FFE4C7', // Fallback color
  backgroundImage: 'linear-gradient(93.72deg, #FFE4C7 0.74%, #F2F0E0 99.23%)',
  borderRadius: 12,
  padding: 10,
  alignItems: 'center',
  justifyContent: 'space-between',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
promotionImage: {
  width: 160,
  height: 100,
},
promotionTextContainer: {
  flex: 1,
  marginRight: 10,
  alignItems: 'flex-end',
},
promotionHeader: {
  fontFamily: 'Alexandria',
  fontWeight: '400',
  fontSize: 14,
  lineHeight: 15,
  color: '#E68314',
  marginBottom: 5,
  textAlign: 'right',
},
promotionSubheader: {
  fontFamily: 'Alexandria',
  fontWeight: '400',
  fontSize: 8,
  lineHeight: 8,
  color: '#E29547',
  marginBottom: 10,
  textAlign: 'right',
},
promotionLink: {
  fontFamily: 'Alexandria',
  fontWeight: '400',
  fontSize: 10,
  lineHeight: 10,
  color: '#000000ff',
  textDecorationLine: 'underline',
  textAlign: 'right',
},
suppliesContainer: {
  backgroundColor: '#fff',
  paddingVertical: 20,
  paddingHorizontal: 15,
},
suppliesHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 15,
  paddingHorizontal: 5,
},
suppliesTitle: {
  fontFamily: 'Alexandria',
  fontWeight: '700',
  fontSize: 16,
  lineHeight: 16,
  color: '#000',
},
suppliesScrollView: {
  paddingVertical: 3,
},
supplyCard: {
  width: 160,
  backgroundColor: '#fff',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E8E8E8',
  marginRight: 15,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
  overflow: 'hidden',
},
supplyImageContainer: {
  position: 'relative',
},
supplyImage: {
  width: '100%',
  height: 120,
},
wishlistIconContainer: {
  position: 'absolute',
  top: 8,
  right: 8,
  width: 24,
  height: 24,
  justifyContent: 'center',
  alignItems: 'center',
},
wishlistIcon: {
  width: 30,
  height: 30,
},
supplyInfo: {
  padding: 12,
},
supplyTitle: {
  fontFamily: 'Alexandria',
  fontWeight: '500',
  fontSize: 12,
  lineHeight: 18,
  color: '#000',
  textAlign: 'right',
  marginBottom: 10,
},
priceRatingContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
},
supplyPrice: {
  fontFamily: 'Alexandria',
  fontWeight: '600',
  fontSize: 12,
  color: '#000',
},
supplyRating: {
  flexDirection: 'row',
  alignItems: 'center',
},
singleRatingContainer: {
  flexDirection: 'row',
  alignItems: 'center',
},
singleStarIcon: {
  width: 12,
  height: 12,
  marginLeft: 4,
},
singleRatingText: {
  fontFamily: 'Alexandria',
  fontWeight: '400',
  fontSize: 10,
  color: '#666',
},
groupImageContainer: {
  width: '100%',
  paddingHorizontal: 0,
  marginVertical: 20,
},
groupImage: {
  width: '100%',
  height: 350, // Adjust height as needed
  resizeMode: 'cover',
},


});